FROM rasa/rasa
USER root 
ENV BOT_ENV=production
COPY . /var/www
WORKDIR /var/www
RUN pip install --upgrade pip
RUN pip install rasa
RUN rasa train

CMD [ "run", "-m", "/app/models", "--enable-api", "--cors", "*", "--debug"]